# Generated by Django 6.0 on 2025-12-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_customer_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
    ]
